### PR TITLE
Updated jackson-databind version to 2.9.10

### PR DESCRIPTION
**Pull request by mibo**
Updated jackson-databind version to 2.9.10 which contains fix for several CVEs (for details see [2.9.10 release notes](https://github.com/FasterXML/jackson/wiki/Jackson-Release-2.9.10)).

### CODE REVIEW

**Comment by scti1016** [comment]
Hi mibo,

Can you please merge into the master?

Best Regards,
scti1016

**Comment by mibo** [comment]
Hi @scti1016, 

I only created this PR and have no permission to merge it into the master.
This must be done by one of the project maintainers.

Regards, Michael

**Comment by thrinethra99** [comment]
Can Someone please merge this change to Master

**Comment by scottfrederick** [comment]
superceded by #305

**Pull request closed without merging**
