### PR TITLE
spring-cloud-connector fails to detect MongoDB service broker (DNS Seedlist Connection Format) in PCF

### PR DESCRIPTION
**Pull request by MikeQin**
Since MongoDB 3.6, MongoDB supports "**DNS Seedlist Connection Format**", which means the connection string looks like this: `mongodb+srv://server.example.com/`.

However, when deploying my Spring Boot app to PCF, my app failed to bind the MongoDB service broker due to the fact that my app couldn't find any proper MongoDB service broker to bind. The exception was:

> org.springframework.cloud.CloudException: No suitable ServiceConnectorCreator found

After working with infrastructure engineers, we've figured out that adding a tag `mongodb` to MongoDB service broker helps solve the issue. 

**It means without the `mongodb` tag, `spring-cloud-cloudfoundry-connector` and `spring-cloud-spring-service-connector` failed to auto scan `mongodb+srv` protocol format for detecting MongoDB service broker, and eventually failed to bind the app to the MongoDB service broker during deployment**.

The current remedy to the issue is to add a `mongodb` tag to MongoDB service broker configuration.

The Spring Boot app `build.gradle` is attached for your reference.

```
plugins {
	id 'org.springframework.boot' version '2.1.6.RELEASE'
	id 'java'
}

apply plugin: 'io.spring.dependency-management'

group = 'com.exaple'
version = '1.0'
sourceCompatibility = '11'
targetCompatibility = '11'

configurations {
	developmentOnly
	runtimeClasspath {
		extendsFrom developmentOnly
	}
	compileOnly {
		extendsFrom annotationProcessor
	}
}

repositories {
	mavenCentral()
}

dependencies {
	implementation 'org.springframework.boot:spring-boot-starter-data-mongodb'
	implementation 'org.springframework.boot:spring-boot-starter-web'
	implementation 'org.springframework.cloud:spring-cloud-spring-service-connector'
	implementation 'org.springframework.cloud:spring-cloud-cloudfoundry-connector'
	compileOnly 'org.projectlombok:lombok'
	developmentOnly 'org.springframework.boot:spring-boot-devtools'
	annotationProcessor 'org.projectlombok:lombok'
	testImplementation 'org.springframework.boot:spring-boot-starter-test'
}
```

### CODE REVIEW

**Comment by pivotal-issuemaster** [comment]
@MikeQin Please sign the [Contributor License Agreement](https://cla.pivotal.io/sign/spring?repositoryId=spring-cloud/spring-cloud-connectors&pullRequestId=310)!

[Click here](https://cla.pivotal.io/sync/spring?repositoryId=spring-cloud/spring-cloud-connectors&pullRequestId=310) to manually synchronize the status of this Pull Request.

See the [FAQ](https://cla.pivotal.io/about) for frequently asked questions.

**Comment by scottfrederick** [comment]
@MikeQin This was submitted as a Pull Request to merge a large set of outdated commits from the `1.x` branch of this project to the `master` branch. I'm not sure what you were trying to do, but that's not going to work.

**Comment by MikeQin** [comment]
> @MikeQin This was submitted as a Pull Request to merge a large set of outdated commits from the `1.x` branch of this project to the `master` branch. I'm not sure what you were trying to do, but that's not going to work.

Hi Scott, thanks for getting back to me. Where is the right place to submit an issue or create a pull request for the problem in question?

**Comment by MikeQin** [comment]
I created an issue instead of a pull request. Thanks.

**Pull request closed without merging**
