### PR TITLE
GitHub issue #112: Allow authSource in the Mongo URI to be passed along

### PR DESCRIPTION
**Pull request by rob-baily**
Also see comment in GitHub issue.
* Update Spring Data Mongo version (to 1.6.2) to support getting MongoCredentials class which has source property.
* Change MongoDbFactoryCreator to use different constructor for SimpleMongoDbFactory.
* Modify tests in MongoDbFactoryCloudConfigTestHelper that used deprecated functions based on version upgrade.
 Other item:
 * Update dependency version for propdeps-plugin to allow build to work in newer version of IntelliJ.

### CODE REVIEW

**Comment by rob-baily** [comment]
Per other comment make minimum Spring Data Mongo version at 1.4.3.  Updated test matrix for Mongo from 1.4.3 to 1.7.0.

**Comment by scottfrederick** [comment]
Fix for #112

**Comment by scottfrederick** [comment]
Merged via https://github.com/spring-cloud/spring-cloud-connectors/commit/c9e4dfa47cc4cf7de95100641675adfc0c3c5272. 

@rob-baily I had to manually merge this PR with https://github.com/spring-cloud/spring-cloud-connectors/pull/115. If you can test this and make sure it works before the next release, I'd appreciate it.

**Comment by rob-baily** [comment]
@scottfrederick  Yes your merge looks good and I confirmed it this morning.  I set up a user in the admin database and modified this in my spring-cloud.properties file since I am using local connect.

spring.cloud.mongo: mongodb://rbaily:development2@localhost:27017/mydb?authSource=admin

I verified it failed without the user in the admin DB and worked with it.

**Pull request closed without merging**
