### PR TITLE
Add support for CloudFoundry NFS and SMB volumes

### PR DESCRIPTION
**Pull request by paulcwarren**
Hi Folks,

CloudFoundry Persistence team here.  We would like to add support for our Volume Services into your Spring Cloud Connector library.  

When we originally added volume services to CF, we updated the open service broker API to include a [volume mount specification](https://github.com/openservicebrokerapi/servicebroker/blob/v2.14/spec.md#volume-mount-object) for service brokers to follow.  This means that any service broker could issue volume mounts to CF.  Our team manages a number of such brokers including our `nfs` and our `smb` broker that are both GAed in cf-deployment and Pivotal Application Service.  Given the volume_mount specification standard, our original intention for this PR was to have a connector that is able to surface any volume mount, regardless of the broker that issued it, as a bean in the Spring application by, for example, implementing an accept method in a `VolumeServiceInfoCreator` like so:

```
	@Override
	public boolean accept(Map<String, Object> serviceData) {
		return containsVolumeMounts(serviceData);
	}
``` 

However, when multiple volumes are bound to the same application from different services, [this exception](https://github.com/spring-cloud/spring-cloud-connectors/blob/9a376333c45efe0b1a99bee0da5b868ce44201bd/spring-cloud-core/src/main/java/org/springframework/cloud/Cloud.java#L196) is thrown since the `VolumeServiceInfoCreator.accept` matches all volume service infos.  This led us down a path of having to create separate Nfs and Smb everything.  This, therefore, means that if we add additional volume service brokers (as we are very likely to do) we'll have to come back and add them here too.  It feels like there should be a better way but we couldn't see it.  It would be very nice if this PR could be refactored to handle any volume mount and we would be very happy to do so after the appropriate pointers.  If not then we are happy with the current implementation and will add stories to our backlog to update these cloud connectors whenever we add new brokers.  

[#164283399](https://www.pivotaltracker.com/story/show/164283399)

Thanks much,
_Paul

@davewalter @julian-hj

### CODE REVIEW

**Comment by scottfrederick** [comment]
@paulcwarren This looks like it could be useful to app developers. 

This core Spring Cloud Connectors library includes support for some of the more common cloud services like databases and messaging services that are available on the supported cloud platforms (Cloud Foundry and Heroku). Our goal is to keep this core library as small as possible. 

Connectors provides an extension mechanism to allow developers to create support for additional services in their own extension libraries. Examples of these extensions can be found under `Community Extensions` on the [project page](https://spring.io/projects/spring-cloud-connectors/). 

Especially in light of the fact that these services are only available on Cloud Foundry, it would be better to create a new extension project for this code. The code should work as-is if it is packaged in its own jar file(s), so it's mainly a matter of its own repo and build files, and publishing the built artifacts.

**Comment by paulcwarren** [comment]
Thanks @scottfrederick.  I understand the need to keep the base library small including services that are cross-cutting where possible  That makes sense.  

That said the reason we PRed to this repo specifically was to be able to participate the auto-reconfiguration that happens when you push Spring apps where your app is automatically re-bound to the cloud services.  If we created a separate community library would there be a way to do that other than telling Developers they have to first put our library on their class-path?

**Comment by scottfrederick** [comment]
> when you push Spring apps where your app is automatically re-bound to cloud services.
> If we created a separate community library would there be a way to do that other than telling Developers they have to first put our library on their class-path?

There are a few different potential answers to this, depending on what you are hoping to do. And it's a bit confusing, unfortunately. 

The Cloud Foundry Java Buildpack has a feature called auto-*re*configuration. With this enabled, JBP will look for connection beans of certain types in a Spring app, look for bound cloud services of the same type, and *replace* existing Spring beans with cloud-configured beans. This is only supported for a [very small set of connection types](https://github.com/cloudfoundry/java-buildpack-auto-reconfiguration), and isn't intended for production use as it gives the app developer little control over the service connection details. It's not feasible (or desirable, really) to extend this to additional types of services. 

Spring Cloud Connectors provides the ability to automatically configure connections beans for bound services (that is, create connection beans as opposed to *reconfiguring* existing beans). This happens automatically with the Spring Boot `spring-boot-starter-cloud-connectors` library, or when depending on the Connectors libs directly and using [service scanning](https://cloud.spring.io/spring-cloud-connectors/spring-cloud-spring-service-connector.html#_scanning_for_services). This creation of Spring connection beans will happen for connection types in the core Connectors lib and any extension libs on the app's classpath. This is the desired approach, as it provides support for all Connectors extensions and give app developers more control over connection details if they need to override settings. 

Then there's the third, emerging, approach to consuming bound services in a Spring application. The motivation for this new approach is explained in a recent [blog post](https://spring.io/blog/2019/02/15/introducing-java-cfenv-a-new-library-for-accessing-cloud-foundry-services), and centers around better support for Spring Boot applications. If Spring Boot is your primary target (as it probably should be), then you should consider scrapping this Connectors extension and going this route. This would be a two-step process. First, you'd write a Spring Boot autoconfiguration library that supports the creation of connection beans from properties that could be set on a Boot app. Second, you'd write a small [`java-cfenv` extension](https://github.com/pivotal-cf/java-cfenv#supporting-other-services) that contains the logic to detect the service type and map from bound services credentials to your new Boot autoconfiguration properties.

**Comment by scottfrederick** [comment]
Closing this PR as the desired functionality is being addressed via [java-cfenv](https://github.com/pivotal-cf/java-cfenv/pull/47) instead.

**Pull request closed without merging**
